import type {
  CommonIndicator,
  UispIndicatorRow,
  LtpRow,
  EvaluationRow,
  DocumentDef,
  Division,
  YearStatus,
  EvidenceStatus,
} from "./types";

export const CURRENT_PERIOD = "2026학년도 1학기";
export const CURRENT_YEAR = 2026;

// 장기발전계획·대학기관평가인증은 2023년(장신비전 2030 4단계 시작)부터,
// 대학혁신지원사업은 2025년부터 연도별 자료를 관리한다.
export const YEARS = [2023, 2024, 2025, 2026] as const;
export const UISP_YEARS = [2025, 2026] as const;

export const DIVISIONS: Division[] = [
  "신학과",
  "기독교교육과",
  "교회음악학과",
  "자유전공",
  "신대원",
  "대학원",
];
export const UNDERGRAD_DIVISIONS: Division[] = ["신학과", "기독교교육과", "교회음악학과", "자유전공"];

export function undergradTotal(byDivision: Record<Division, number>) {
  return (
    byDivision["신학과"] +
    byDivision["기독교교육과"] +
    byDivision["교회음악학과"] +
    byDivision["자유전공"]
  );
}

// ---------------------------------------------------------------------------
// 연도별·소속별 더미 데이터 생성 헬퍼
// ---------------------------------------------------------------------------

/** 대학(4개 학과) : 신대원 : 대학원 = 55 : 30 : 15 비율로 배분 */
function splitByDivision(total: number): Record<Division, number> {
  const ratios: [Division, number][] = [
    ["신학과", 0.25],
    ["기독교교육과", 0.12],
    ["교회음악학과", 0.08],
    ["자유전공", 0.1],
    ["신대원", 0.3],
    ["대학원", 0.15],
  ];
  const rounded = ratios.map(([d, r]) => [d, Math.round(total * r)] as const);
  const diff = total - rounded.reduce((sum, [, v]) => sum + v, 0);
  return Object.fromEntries(rounded.map(([d, v], i) => [d, i === 0 ? v + diff : v])) as Record<
    Division,
    number
  >;
}

/** 과거 연도 값을 완만한 성장 곡선으로 역산 (연 12% 내외 증가 추세 가정) */
function backdate(current: number, yearsBack: number, decimals = 0): number {
  if (yearsBack <= 0) return current;
  const factor = Math.pow(0.88, yearsBack);
  const v = current * factor;
  return decimals > 0 ? Math.round(v * 10 ** decimals) / 10 ** decimals : Math.max(0, Math.round(v));
}

/** target이 0인 지표(실적만 있고 목표가 없는 경우)의 0으로 나누기 방지 */
function attainmentPct(actual: number, target: number): number {
  if (target === 0) return actual > 0 ? 100 : 0;
  return Math.round((actual / target) * 100);
}

function parseLeadingNumber(
  text: string
): { num: number; prefix: string; suffix: string; decimals: number } | null {
  const m = text.match(/^(.*?)(\d+(?:\.\d+)?)(.*)$/);
  if (!m) return null;
  const [, prefix, numStr, suffix] = m;
  const decimals = numStr.includes(".") ? numStr.split(".")[1].length : 0;
  return { num: parseFloat(numStr), prefix, suffix, decimals };
}

function ltpYearSeries(actual: string, currentYear = CURRENT_YEAR) {
  const parsed = parseLeadingNumber(actual);
  return YEARS.map((year) => {
    const status: YearStatus = year === currentYear ? "입력가능" : "완료";
    if (!parsed) return { year, actual, actualValue: 0, status };
    const yearsBack = currentYear - year;
    const value = backdate(parsed.num, yearsBack, parsed.decimals);
    const formatted = parsed.decimals > 0 ? value.toFixed(parsed.decimals) : String(value);
    return {
      year,
      actual: `${parsed.prefix}${formatted}${parsed.suffix}`,
      actualValue: value,
      status,
    };
  });
}

function evalYearSeries(
  relatedPerformance: string,
  evidenceStatus: EvidenceStatus,
  currentYear = CURRENT_YEAR
) {
  const parsed = parseLeadingNumber(relatedPerformance);
  return YEARS.map((year) => {
    const status: YearStatus = year === currentYear ? "입력가능" : "완료";
    let rp = relatedPerformance;
    if (parsed) {
      const yearsBack = currentYear - year;
      const value = backdate(parsed.num, yearsBack, parsed.decimals);
      const formatted = parsed.decimals > 0 ? value.toFixed(parsed.decimals) : String(value);
      rp = `${parsed.prefix}${formatted}${parsed.suffix}`;
    }
    return {
      year,
      relatedPerformance: rp,
      evidenceStatus: status === "완료" ? ("제출완료" as EvidenceStatus) : evidenceStatus,
      status,
    };
  });
}

function uispYearSeries(
  baseline: number,
  target: number,
  actual: number,
  real2025?: { baseline: number; target: number },
  currentYear = CURRENT_YEAR
) {
  return UISP_YEARS.map((year) => {
    if (year === currentYear) {
      return { year, baseline, target, actual, status: "입력가능" as YearStatus };
    }
    return {
      year,
      baseline: real2025?.baseline ?? backdate(baseline, 1),
      target: real2025?.target ?? backdate(target, 1),
      // 2026년 신규 실적이 아직 반영되지 않아, 2025년 마감 실적을 그대로 표시
      actual,
      status: "완료" as YearStatus,
    };
  });
}

// ---------------------------------------------------------------------------
// 1) 교육혁신처 기준 공통 실적 데이터 10종
//    -> 장기발전계획 / 대학기관평가인증 / 대학혁신지원사업 3개 장표와의 연계 매핑
//    소속(대학 3개 학과·신대원·대학원)별로 분포하며, 대학혁신지원사업에는
//    이 중 대학(학부) 몫만 반영된다.
// ---------------------------------------------------------------------------
export const COMMON_INDICATORS: CommonIndicator[] = [
  {
    field: "edutech_course_count",
    sourceLabel: "에듀테크 활용 교과목 운영 수",
    metricKind: "건수",
    value: 18,
    unit: "개",
    dept: "교육혁신처",
    period: CURRENT_PERIOD,
    group: "에듀테크·혁신교수법",
    byDivision: splitByDivision(18),
    uisp: {
      area: "C",
      code: "C111",
      indicator: "에듀테크 활용 교과 운영 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "교육혁신 체계 고도화",
      action: "에듀테크 기반 수업환경 조성",
      indicator: "에듀테크 활용 교과목 운영 수",
    },
    evaluation: {
      area: "교육과정 운영 및 개선",
      item: "교육과정의 다양화·특성화",
      material: "에듀테크 활용 교과목 운영 현황",
    },
  },
  {
    field: "innovative_teaching_course_count",
    sourceLabel: "혁신교수법 적용 교과목 수",
    metricKind: "건수",
    value: 24,
    unit: "개",
    dept: "교육혁신처",
    period: CURRENT_PERIOD,
    group: "에듀테크·혁신교수법",
    byDivision: splitByDivision(24),
    uisp: {
      area: "C",
      code: "C112",
      indicator: "혁신교수법 적용 교과 운영 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "미래형 교수학습 지원 강화",
      action: "혁신교수법(PBL·플립러닝 등) 확산",
      indicator: "혁신교수법 적용 교과목 수",
    },
    evaluation: {
      area: "교수학습 지원 체계",
      item: "교수법 다양화 및 학습자 중심 수업 운영",
      material: "혁신교수법 적용 교과목 목록 및 강의계획서",
    },
  },
  {
    field: "teaching_workshop_count",
    sourceLabel: "교수법 워크숍 운영 건수",
    metricKind: "건수",
    value: 6,
    unit: "건",
    dept: "교수학습개발원",
    period: CURRENT_PERIOD,
    group: "교수역량 워크숍",
    byDivision: splitByDivision(6),
    uisp: {
      area: "C",
      code: "C131",
      indicator: "교수역량 강화 프로그램(기존) 운영 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "미래형 교수학습 지원 강화",
      action: "교원 교수역량 강화 워크숍 운영",
      indicator: "교수법 워크숍 운영 건수",
    },
    evaluation: {
      area: "교수학습 지원 체계",
      item: "교원 교수역량 개발 지원",
      material: "워크숍 운영계획 및 결과보고서",
    },
  },
  {
    field: "teaching_workshop_participant_count",
    sourceLabel: "워크숍 참여 교원 수",
    metricKind: "교원 수",
    value: 86,
    unit: "명",
    dept: "교수학습개발원",
    period: CURRENT_PERIOD,
    group: "교수역량 워크숍",
    byDivision: splitByDivision(86),
    uisp: {
      area: "C",
      code: "C232",
      indicator: "강화 프로그램 참여 교원 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "미래형 교수학습 지원 강화",
      action: "교원 교수역량 강화 워크숍 운영",
      indicator: "워크숍 참여 교원 수",
    },
    evaluation: {
      area: "교수학습 지원 체계",
      item: "교원 교수역량 개발 지원",
      material: "워크숍 참여자 명단",
    },
  },
  {
    field: "cqi_report_count",
    sourceLabel: "교과목 CQI 참여율",
    metricKind: "건수",
    value: 132,
    unit: "개",
    dept: "교육혁신처",
    period: CURRENT_PERIOD,
    group: "성과분석·환류",
    byDivision: splitByDivision(132),
    uisp: {
      area: "C",
      code: "C121",
      indicator: "CQI 입력 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "수업 질 관리 체계 강화",
      action: "CQI 환류 체계 운영",
      indicator: "교과목 CQI 참여율",
    },
    evaluation: {
      area: "교육성과 분석 및 환류",
      item: "강의평가 및 CQI 환류체계 운영",
      material: "CQI 보고서",
    },
  },
  {
    field: "student_competency_diagnosis_count",
    sourceLabel: "역량진단 참여 학생 수",
    metricKind: "학생 수",
    value: 246,
    unit: "명",
    dept: "혁신성과관리센터(IR)",
    period: CURRENT_PERIOD,
    group: "학생역량·비교과",
    byDivision: splitByDivision(246),
    uisp: {
      area: "C",
      code: "C221",
      indicator: "역량진단・강화 프로그램(기존) 참여 학생 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "학생역량 기반 교육성과 관리",
      action: "핵심역량 진단검사 실시",
      indicator: "역량진단 참여 학생 수",
    },
    evaluation: {
      area: "학생역량 관리",
      item: "학생 핵심역량 진단·관리 체계",
      material: "역량진단 결과보고서",
    },
  },
  {
    field: "extracurricular_program_participant_count",
    sourceLabel: "비교과 프로그램 참여 학생 수",
    metricKind: "학생 수",
    value: 418,
    unit: "명",
    dept: "학생처",
    period: CURRENT_PERIOD,
    group: "학생역량·비교과",
    byDivision: splitByDivision(418),
    uisp: {
      area: "B",
      code: "B24",
      indicator: "PUTS+마일리지・인증제 참여 학생 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "학생역량 기반 교육성과 관리",
      action: "비교과 프로그램 운영 및 참여 확대",
      indicator: "비교과 프로그램 참여 학생 수",
    },
    evaluation: {
      area: "학생역량 관리",
      item: "비교과 교육과정 운영 실적",
      material: "비교과 프로그램 참여자 명단",
    },
  },
  {
    field: "lms_course_count",
    sourceLabel: "LMS 활용 교과목 수",
    metricKind: "건수",
    value: 156,
    unit: "개",
    dept: "교육혁신처",
    period: CURRENT_PERIOD,
    group: "에듀테크·혁신교수법",
    byDivision: splitByDivision(156),
    // uisp.vercel.app 자율성과지표에는 "LMS 이용자 수(D21)"만 있고 "교과목 수" 단위의
    // 동일 지표가 없어 UISP 연계는 아직 없음 (장기발전계획·대학기관평가인증에서만 활용)
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "교육혁신 체계 고도화",
      action: "LMS 기반 학습관리 확대",
      indicator: "LMS 활용 교과목 수",
    },
    evaluation: {
      area: "교수학습 지원 체계",
      item: "학습관리시스템(LMS) 운영 실적",
      material: "LMS 활용 교과목 현황",
    },
  },
  {
    field: "education_outcome_report_count",
    sourceLabel: "교육성과 분석보고서 작성 건수",
    metricKind: "건수",
    value: 4,
    unit: "건",
    dept: "혁신성과관리센터(IR)",
    period: CURRENT_PERIOD,
    group: "성과분석·환류",
    byDivision: splitByDivision(4),
    // uisp.vercel.app에는 보고서 "작성 건수"를 세는 지표가 없어 UISP 연계는 아직 없음
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "수업 질 관리 체계 강화",
      action: "교육성과 분석 및 확산",
      indicator: "교육성과 분석보고서 작성 건수",
    },
    evaluation: {
      area: "교육성과 분석 및 환류",
      item: "교육성과 분석체계 구축·운영",
      material: "교육성과 분석 보고서",
    },
  },
  {
    field: "teaching_improvement_feedback_count",
    sourceLabel: "수업개선 환류 사례 수",
    metricKind: "건수",
    value: 12,
    unit: "건",
    dept: "교무처",
    period: CURRENT_PERIOD,
    group: "성과분석·환류",
    byDivision: splitByDivision(12),
    // uisp.vercel.app에는 "환류 사례 수"에 대응하는 지표가 없어 UISP 연계는 아직 없음
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "수업 질 관리 체계 강화",
      action: "CQI 환류 체계 운영",
      indicator: "수업개선 환류 사례 수",
    },
    evaluation: {
      area: "교육성과 분석 및 환류",
      item: "환류 결과의 활용 실적",
      material: "수업개선 사례집",
    },
  },
];


// ---------------------------------------------------------------------------
// 2) 대학혁신지원사업 (UISP) — uisp.vercel.app 실제 자율성과지표 A~D 체계 그대로 사용
//    (지표 코드·지표명·담당부서는 yenna-ai/uisp 저장소의 Indicators.csv / Users.csv 기준)
//    linkedField 가 있는 행은 교육혁신처 공통 데이터 중 "대학(학부)" 몫만 반영된 지표
//    (대학혁신지원사업은 학부교육 대상 사업이므로 신대원·대학원 실적은 제외)
// ---------------------------------------------------------------------------
export const UISP_AREAS = [
  { code: "A", name: "학사 유연화 지수", short: "학사 유연화" },
  { code: "B", name: "학생성장 지원 지수", short: "학생성장 지원" },
  { code: "C", name: "PUTS형 교육혁신 지수", short: "PUTS형 교육혁신" },
  { code: "D", name: "교육환경 고도화 지수", short: "교육환경 고도화" },
] as const;

const UISP_INDICATORS_BASE: (Omit<UispIndicatorRow, "years" | "baseline" | "target" | "actual"> & {
  baseline: number; target: number; actual: number;
  real2025: { baseline: number; target: number };
})[] = [
  {
    id: "A11",
    area: "A",
    code: "A11",
    indicator: "자유전공 전공탐색 교과 개발 수",
    dept: "교육혁신처",
    baseline: 0,
    target: 2,
    actual: 3,
    unit: "건",
    real2025: { baseline: 0, target: 1 },
  },
  {
    id: "A12",
    area: "A",
    code: "A12",
    indicator: "교양・기초교육 신규교과 개발 수",
    dept: "교육혁신처",
    baseline: 4,
    target: 6,
    actual: 0,
    unit: "건",
    real2025: { baseline: 4, target: 5 },
  },
  {
    id: "A13",
    area: "A",
    code: "A13",
    indicator: "연계・융합전공 교과 개발 수",
    dept: "교육혁신처",
    baseline: 0,
    target: 2,
    actual: 1,
    unit: "건",
    real2025: { baseline: 0, target: 1 },
  },
  {
    id: "A14",
    area: "A",
    code: "A14",
    indicator: "유연학사제 기반 구축 프로그램 운영 수",
    dept: "교육혁신처",
    baseline: 4,
    target: 6,
    actual: 0,
    unit: "건",
    real2025: { baseline: 4, target: 5 },
  },
  {
    id: "A21",
    area: "A",
    code: "A21",
    indicator: "자유전공 참여 학생 수",
    dept: "교학실(대학)",
    baseline: 0,
    target: 20,
    actual: 24,
    unit: "명",
    real2025: { baseline: 0, target: 20 },
  },
  {
    id: "A22",
    area: "A",
    code: "A22",
    indicator: "교양・기초교육 신규교과 참여 학생 수",
    dept: "교학실(대학)",
    baseline: 100,
    target: 102,
    actual: 381,
    unit: "명",
    real2025: { baseline: 100, target: 101 },
  },
  {
    id: "A231",
    area: "A",
    code: "A231",
    indicator: "진로연계교육과정 참여 학생 수",
    dept: "교학실(대학)",
    baseline: 71,
    target: 71,
    actual: 61,
    unit: "명",
    real2025: { baseline: 71, target: 71 },
  },
  {
    id: "A232",
    area: "A",
    code: "A232",
    indicator: "학-석사 연계과정 참여 학생 수",
    dept: "교학실(대학)",
    baseline: 5,
    target: 7,
    actual: 4,
    unit: "명",
    real2025: { baseline: 5, target: 6 },
  },
  {
    id: "A233",
    area: "A",
    code: "A233",
    indicator: "연계・융합전공 참여 학생 수",
    dept: "교학실(대학)",
    baseline: 0,
    target: 2,
    actual: 0,
    unit: "명",
    real2025: { baseline: 0, target: 1 },
  },
  {
    id: "A31",
    area: "A",
    code: "A31",
    indicator: "자유전공 만족도 평균",
    dept: "교학실(대학)",
    baseline: 0,
    target: 67,
    actual: 90,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "A32",
    area: "A",
    code: "A32",
    indicator: "교양・기초교육 신규교과 만족도 평균",
    dept: "교학실(대학)",
    baseline: 92.2,
    target: 92.8,
    actual: 91.2,
    unit: "점",
    real2025: { baseline: 92.2, target: 92.5 },
  },
  {
    id: "A33",
    area: "A",
    code: "A33",
    indicator: "진로연계교육과정 만족도 평균",
    dept: "교학실(대학)",
    baseline: 73.3,
    target: 75.3,
    actual: 90,
    unit: "점",
    real2025: { baseline: 73.3, target: 73.3 },
  },
  {
    id: "A34",
    area: "A",
    code: "A34",
    indicator: "학-석사 연계과정 만족도 평균",
    dept: "교육혁신처",
    baseline: 0,
    target: 67,
    actual: 82.4,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "A35",
    area: "A",
    code: "A35",
    indicator: "연계・융합전공 만족도 평균",
    dept: "교육혁신처",
    baseline: 0,
    target: 67,
    actual: 0,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "B11",
    area: "B",
    code: "B11",
    indicator: "기초학습역량 프로그램 운영 수",
    dept: "교육혁신처(CTL)",
    baseline: 20,
    target: 22,
    actual: 22,
    unit: "건",
    real2025: { baseline: 20, target: 21 },
  },
  {
    id: "B12",
    area: "B",
    code: "B12",
    indicator: "맞춤형 전공・진로탐색 프로그램 운영 수",
    dept: "교학실(대학)",
    baseline: 5,
    target: 6,
    actual: 6,
    unit: "건",
    real2025: { baseline: 5, target: 5 },
  },
  {
    id: "B131",
    area: "B",
    code: "B131",
    indicator: "글로컬 현장 프로그램 운영 수",
    dept: "글로컬현장교육원",
    baseline: 2,
    target: 4,
    actual: 5,
    unit: "건",
    real2025: { baseline: 2, target: 3 },
  },
  {
    id: "B132",
    area: "B",
    code: "B132",
    indicator: "사회봉사(기존) 프로그램 운영 수",
    dept: "글로컬현장교육원",
    baseline: 4,
    target: 8,
    actual: 6,
    unit: "건",
    real2025: { baseline: 4, target: 6 },
  },
  {
    id: "B133",
    area: "B",
    code: "B133",
    indicator: "ESG 연계 프로그램 운영 수",
    dept: "관리실",
    baseline: 4,
    target: 6,
    actual: 5,
    unit: "건",
    real2025: { baseline: 4, target: 5 },
  },
  {
    id: "B134",
    area: "B",
    code: "B134",
    indicator: "사회봉사(추가) 프로그램 운영 수",
    dept: "기획실",
    baseline: 0,
    target: 0,
    actual: 1,
    unit: "건",
    real2025: { baseline: 0, target: 0 },
  },
  {
    id: "B21",
    area: "B",
    code: "B21",
    indicator: "기초학습역량 프로그램 참여 학생 수",
    dept: "교육혁신처(CTL)",
    baseline: 364,
    target: 386,
    actual: 400,
    unit: "명",
    real2025: { baseline: 364, target: 375 },
  },
  {
    id: "B22",
    area: "B",
    code: "B22",
    indicator: "맞춤형 전공・진로탐색 참여 학생 수",
    dept: "교학실(대학)",
    baseline: 418,
    target: 461,
    actual: 354,
    unit: "명",
    real2025: { baseline: 418, target: 439 },
  },
  {
    id: "B23",
    area: "B",
    code: "B23",
    indicator: "학생생활상담・멘토링 참여 학생 수",
    dept: "교육혁신처",
    baseline: 1761,
    target: 1941,
    actual: 0,
    unit: "명",
    real2025: { baseline: 1761, target: 1849 },
  },
  {
    id: "B24",
    area: "B",
    code: "B24",
    indicator: "PUTS+마일리지・인증제 참여 학생 수",
    dept: "교육혁신처",
    baseline: 0,
    target: 114,
    actual: 14,
    unit: "명",
    real2025: { baseline: 0, target: 57 },
    linkedField: "extracurricular_program_participant_count",
  },
  {
    id: "B251",
    area: "B",
    code: "B251",
    indicator: "글로컬 현장 참여 학생 수",
    dept: "글로컬현장교육원",
    baseline: 27,
    target: 28,
    actual: 28,
    unit: "명",
    real2025: { baseline: 27, target: 28 },
  },
  {
    id: "B252",
    area: "B",
    code: "B252",
    indicator: "사회봉사(기존) 참여 학생 수",
    dept: "글로컬현장교육원",
    baseline: 34,
    target: 35,
    actual: 47,
    unit: "명",
    real2025: { baseline: 34, target: 35 },
  },
  {
    id: "B253",
    area: "B",
    code: "B253",
    indicator: "ESG 연계 참여 학생 수",
    dept: "관리실",
    baseline: 47,
    target: 48,
    actual: 336,
    unit: "명",
    real2025: { baseline: 47, target: 47 },
  },
  {
    id: "B31",
    area: "B",
    code: "B31",
    indicator: "기초학습역량 프로그램 만족도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 76.4,
    target: 77.4,
    actual: 92,
    unit: "점",
    real2025: { baseline: 76.4, target: 76.9 },
  },
  {
    id: "B32",
    area: "B",
    code: "B32",
    indicator: "맞춤형 전공・진로탐색 만족도 평균",
    dept: "교학실(대학)",
    baseline: 95.1,
    target: 95.7,
    actual: 92.8,
    unit: "점",
    real2025: { baseline: 95.1, target: 95.4 },
  },
  {
    id: "B33",
    area: "B",
    code: "B33",
    indicator: "학생생활상담・멘토링 만족도 평균",
    dept: "교육혁신처",
    baseline: 72.9,
    target: 73.9,
    actual: 0,
    unit: "점",
    real2025: { baseline: 72.9, target: 73.4 },
  },
  {
    id: "B34",
    area: "B",
    code: "B34",
    indicator: "PUTS+마일리지・인증제 만족도 평균",
    dept: "교육혁신처",
    baseline: 0,
    target: 67,
    actual: 84.2,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "B351",
    area: "B",
    code: "B351",
    indicator: "글로컬 현장 만족도 평균",
    dept: "글로컬현장교육원",
    baseline: 72.2,
    target: 73.2,
    actual: 96.2,
    unit: "점",
    real2025: { baseline: 72.2, target: 72.7 },
  },
  {
    id: "B352",
    area: "B",
    code: "B352",
    indicator: "사회봉사(기존) 만족도 평균",
    dept: "글로컬현장교육원",
    baseline: 72.8,
    target: 73.8,
    actual: 90.8,
    unit: "점",
    real2025: { baseline: 72.8, target: 73.3 },
  },
  {
    id: "B353",
    area: "B",
    code: "B353",
    indicator: "ESG 연계 만족도 평균",
    dept: "관리실",
    baseline: 0,
    target: 73.5,
    actual: 86.8,
    unit: "점",
    real2025: { baseline: 0, target: 73 },
  },
  {
    id: "B41",
    area: "B",
    code: "B41",
    indicator: "기초학습역량 프로그램 참여학생 역량 향상도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 0,
    target: 67,
    actual: 84.2,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "B42",
    area: "B",
    code: "B42",
    indicator: "맞춤형 전공・진로탐색 참여학생 역량 향상도 평균",
    dept: "교학실(대학)",
    baseline: 0,
    target: 67,
    actual: 87.4,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "B431",
    area: "B",
    code: "B431",
    indicator: "글로컬 현장 역량 향상도 평균",
    dept: "글로컬현장교육원",
    baseline: 0,
    target: 67,
    actual: 88.8,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "B432",
    area: "B",
    code: "B432",
    indicator: "사회봉사(기존) 역량 향상도 평균",
    dept: "글로컬현장교육원",
    baseline: 0,
    target: 67,
    actual: 74.2,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "B433",
    area: "B",
    code: "B433",
    indicator: "ESG 연계 역량 향상도 평균",
    dept: "관리실",
    baseline: 0,
    target: 67,
    actual: 82.8,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "C111",
    area: "C",
    code: "C111",
    indicator: "에듀테크 활용 교과 운영 수",
    dept: "교육혁신처(CTL)",
    baseline: 26,
    target: 28,
    actual: 35,
    unit: "건",
    real2025: { baseline: 26, target: 27 },
    linkedField: "edutech_course_count",
  },
  {
    id: "C112",
    area: "C",
    code: "C112",
    indicator: "혁신교수법 적용 교과 운영 수",
    dept: "교육혁신처(CTL)",
    baseline: 1,
    target: 3,
    actual: 4,
    unit: "건",
    real2025: { baseline: 1, target: 2 },
    linkedField: "innovative_teaching_course_count",
  },
  {
    id: "C121",
    area: "C",
    code: "C121",
    indicator: "CQI 입력 수",
    dept: "교육혁신처(IR)",
    baseline: 89,
    target: 95,
    actual: 134,
    unit: "건",
    real2025: { baseline: 89, target: 91 },
    linkedField: "cqi_report_count",
  },
  {
    id: "C122",
    area: "C",
    code: "C122",
    indicator: "우수 교과 확산 수",
    dept: "교육혁신처(IR)",
    baseline: 0,
    target: 18,
    actual: 10,
    unit: "건",
    real2025: { baseline: 0, target: 10 },
  },
  {
    id: "C131",
    area: "C",
    code: "C131",
    indicator: "교수역량 강화 프로그램(기존) 운영 수",
    dept: "교육혁신처(CTL)",
    baseline: 4,
    target: 6,
    actual: 10,
    unit: "건",
    real2025: { baseline: 4, target: 5 },
    linkedField: "teaching_workshop_count",
  },
  {
    id: "C132",
    area: "C",
    code: "C132",
    indicator: "디지털 소양 함양 프로그램 운영 수",
    dept: "교육혁신처(CTL)",
    baseline: 2,
    target: 4,
    actual: 5,
    unit: "건",
    real2025: { baseline: 2, target: 3 },
  },
  {
    id: "C211",
    area: "C",
    code: "C211",
    indicator: "에듀테크 활용 교과 참여 학생 수",
    dept: "교육혁신처(CTL)",
    baseline: 660,
    target: 680,
    actual: 676,
    unit: "명",
    real2025: { baseline: 660, target: 670 },
  },
  {
    id: "C212",
    area: "C",
    code: "C212",
    indicator: "혁신교수법 적용 교과 참여 학생 수",
    dept: "교육혁신처(CTL)",
    baseline: 63,
    target: 77,
    actual: 114,
    unit: "명",
    real2025: { baseline: 63, target: 70 },
  },
  {
    id: "C221",
    area: "C",
    code: "C221",
    indicator: "역량진단ㆍ강화 프로그램(기존) 참여 학생 수",
    dept: "교육혁신처(IR)",
    baseline: 145,
    target: 160,
    actual: 257,
    unit: "명",
    real2025: { baseline: 145, target: 152 },
    linkedField: "student_competency_diagnosis_count",
  },
  {
    id: "C222",
    area: "C",
    code: "C222",
    indicator: "디지털 소양 함양 프로그램 참여 학생 수",
    dept: "교육혁신처(CTL)",
    baseline: 56,
    target: 62,
    actual: 50,
    unit: "명",
    real2025: { baseline: 56, target: 59 },
  },
  {
    id: "C231",
    area: "C",
    code: "C231",
    indicator: "역량진단 참여 교원 수",
    dept: "교육혁신처(IR)",
    baseline: 60,
    target: 70,
    actual: 61,
    unit: "명",
    real2025: { baseline: 60, target: 65 },
  },
  {
    id: "C232",
    area: "C",
    code: "C232",
    indicator: "강화 프로그램 참여 교원 수",
    dept: "교육혁신처(CTL)",
    baseline: 155,
    target: 155,
    actual: 326,
    unit: "명",
    real2025: { baseline: 155, target: 155 },
    linkedField: "teaching_workshop_participant_count",
  },
  {
    id: "C31",
    area: "C",
    code: "C31",
    indicator: "혁신교수법 적용 교과 만족도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 93.8,
    target: 94,
    actual: 94.8,
    unit: "점",
    real2025: { baseline: 93.8, target: 93.9 },
  },
  {
    id: "C32",
    area: "C",
    code: "C32",
    indicator: "에듀테크 활용 교과 만족도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 93.7,
    target: 93.9,
    actual: 91.2,
    unit: "점",
    real2025: { baseline: 93.7, target: 93.8 },
  },
  {
    id: "C33",
    area: "C",
    code: "C33",
    indicator: "디지털 소양 함양 프로그램 만족도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 93.5,
    target: 93.7,
    actual: 94.6,
    unit: "점",
    real2025: { baseline: 93.5, target: 93.6 },
  },
  {
    id: "C34",
    area: "C",
    code: "C34",
    indicator: "교원 역량 강화 프로그램 만족도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 92.2,
    target: 92.4,
    actual: 91.4,
    unit: "점",
    real2025: { baseline: 92.2, target: 92.3 },
  },
  {
    id: "C41",
    area: "C",
    code: "C41",
    indicator: "학생 핵심역량 진단 점수",
    dept: "교육혁신처(IR)",
    baseline: 79.8,
    target: 79.86,
    actual: 82.4,
    unit: "점",
    real2025: { baseline: 79.8, target: 79.83 },
  },
  {
    id: "C42",
    area: "C",
    code: "C42",
    indicator: "교원 교수역량 진단 점수",
    dept: "교육혁신처(IR)",
    baseline: 90.6,
    target: 90.66,
    actual: 87.4,
    unit: "점",
    real2025: { baseline: 90.6, target: 90.63 },
  },
  {
    id: "C43",
    area: "C",
    code: "C43",
    indicator: "혁신교수법 교과 참여 학생 역량 향상도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 0,
    target: 70,
    actual: 89.2,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "C44",
    area: "C",
    code: "C44",
    indicator: "에듀테크 활용 교과 참여 학생 역량 향상도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 0,
    target: 70,
    actual: 87.2,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "D111",
    area: "D",
    code: "D111",
    indicator: "LMS 개발・운영 수",
    dept: "교육혁신처",
    baseline: 1,
    target: 1,
    actual: 1,
    unit: "건",
    real2025: { baseline: 1, target: 1 },
  },
  {
    id: "D112",
    area: "D",
    code: "D112",
    indicator: "LAMP 개발・운영 수",
    dept: "교육혁신처",
    baseline: 0,
    target: 1,
    actual: 1,
    unit: "건",
    real2025: { baseline: 0, target: 0 },
  },
  {
    id: "D12",
    area: "D",
    code: "D12",
    indicator: "에듀테크 라이선스 확보・지원 수",
    dept: "교육혁신처(CTL)",
    baseline: 78,
    target: 82,
    actual: 86,
    unit: "건",
    real2025: { baseline: 78, target: 80 },
  },
  {
    id: "D13",
    area: "D",
    code: "D13",
    indicator: "디지털 콘텐츠 개발 수",
    dept: "교육혁신처",
    baseline: 26,
    target: 32,
    actual: 0,
    unit: "건",
    real2025: { baseline: 26, target: 29 },
  },
  {
    id: "D21",
    area: "D",
    code: "D21",
    indicator: "LMS 이용자 수",
    dept: "교육혁신처(CTL)",
    baseline: 581,
    target: 583,
    actual: 628,
    unit: "명",
    real2025: { baseline: 581, target: 582 },
  },
  {
    id: "D22",
    area: "D",
    code: "D22",
    indicator: "LAMP 이용자 수",
    dept: "교육혁신처",
    baseline: 0,
    target: 114,
    actual: 14,
    unit: "명",
    real2025: { baseline: 0, target: 57 },
  },
  {
    id: "D23",
    area: "D",
    code: "D23",
    indicator: "에듀테크 및 콘텐츠 이용자 수",
    dept: "교육혁신처(CTL)",
    baseline: 23,
    target: 29,
    actual: 30,
    unit: "명",
    real2025: { baseline: 23, target: 26 },
  },
  {
    id: "D31",
    area: "D",
    code: "D31",
    indicator: "LMS 이용자 만족도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 75.1,
    target: 76,
    actual: 73,
    unit: "점",
    real2025: { baseline: 75.1, target: 75.5 },
  },
  {
    id: "D32",
    area: "D",
    code: "D32",
    indicator: "LAMP 이용자 만족도 평균",
    dept: "교육혁신처",
    baseline: 0,
    target: 70,
    actual: 84.2,
    unit: "점",
    real2025: { baseline: 0, target: 65 },
  },
  {
    id: "D331",
    area: "D",
    code: "D331",
    indicator: "에듀테크 이용자 만족도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 80,
    target: 81,
    actual: 83.4,
    unit: "점",
    real2025: { baseline: 80, target: 80.5 },
  },
  {
    id: "D332",
    area: "D",
    code: "D332",
    indicator: "인프라 이용자 만족도 평균",
    dept: "교육혁신처(CTL)",
    baseline: 73.9,
    target: 74.9,
    actual: 72.6,
    unit: "점",
    real2025: { baseline: 73.9, target: 74.4 },
  },
];


export const UISP_INDICATORS: UispIndicatorRow[] = UISP_INDICATORS_BASE.map((r) => {
  const { real2025, ...rest } = r;
  return {
    ...rest,
    years: uispYearSeries(r.baseline, r.target, r.actual, real2025),
  };
});

// ---------------------------------------------------------------------------
// 3) 장기발전계획(장신비전 2030 4단계) — 교육혁신처 관련 발췌 (2023년~)
// ---------------------------------------------------------------------------
const LTP_ROWS_BASE: Omit<LtpRow, "years">[] = [
  {
    id: "ltp-01",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "교육혁신 체계 고도화",
    action: "에듀테크 기반 수업환경 조성",
    indicator: "에듀테크 활용 교과목 운영 수",
    formula: "에듀테크 활용 교과목 수",
    dept: "교육혁신처",
    actual: "18개",
    target: 15,
    unit: "개",
    linkedField: "edutech_course_count",
  },
  {
    id: "ltp-02",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "교육혁신 체계 고도화",
    action: "LMS 기반 학습관리 확대",
    indicator: "LMS 활용 교과목 수",
    formula: "LMS 활용 교과목 수",
    dept: "교육혁신처",
    actual: "156개",
    target: 140,
    unit: "개",
    linkedField: "lms_course_count",
  },
  {
    id: "ltp-03",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "미래형 교수학습 지원 강화",
    action: "혁신교수법(PBL·플립러닝 등) 확산",
    indicator: "혁신교수법 적용 교과목 수",
    formula: "혁신교수법 적용 교과목 수",
    dept: "교육혁신처",
    actual: "24개",
    target: 20,
    unit: "개",
    linkedField: "innovative_teaching_course_count",
  },
  {
    id: "ltp-04",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "미래형 교수학습 지원 강화",
    action: "교원 교수역량 강화 워크숍 운영",
    indicator: "교수법 워크숍 운영 건수",
    formula: "워크숍 운영 건수",
    dept: "교수학습개발원",
    actual: "6건",
    target: 4,
    unit: "건",
    linkedField: "teaching_workshop_count",
  },
  {
    id: "ltp-05",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "미래형 교수학습 지원 강화",
    action: "교원 교수역량 강화 워크숍 운영",
    indicator: "워크숍 참여 교원 수",
    formula: "워크숍 참여 교원 수",
    dept: "교수학습개발원",
    actual: "86명",
    target: 70,
    unit: "명",
    linkedField: "teaching_workshop_participant_count",
  },
  {
    id: "ltp-06",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "학생역량 기반 교육성과 관리",
    action: "핵심역량 진단검사 실시",
    indicator: "역량진단 참여 학생 수",
    formula: "역량진단 참여 학생 수",
    dept: "혁신성과관리센터(IR)",
    actual: "246명",
    target: 200,
    unit: "명",
    linkedField: "student_competency_diagnosis_count",
  },
  {
    id: "ltp-07",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "학생역량 기반 교육성과 관리",
    action: "비교과 프로그램 운영 및 참여 확대",
    indicator: "비교과 프로그램 참여 학생 수",
    formula: "비교과 프로그램 참여 학생 수(연인원)",
    dept: "학생처",
    actual: "418명",
    target: 350,
    unit: "명",
    linkedField: "extracurricular_program_participant_count",
  },
  {
    id: "ltp-08",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "수업 질 관리 체계 강화",
    action: "CQI 환류 체계 운영",
    indicator: "교과목 CQI 참여율",
    formula: "CQI 제출 교과목 수 / 매 학기 전체 교과목 수 X 100",
    dept: "교육혁신처",
    actual: "132개 제출",
    target: 120,
    unit: "개",
    linkedField: "cqi_report_count",
  },
  {
    id: "ltp-09",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "수업 질 관리 체계 강화",
    action: "교육성과 분석 및 확산",
    indicator: "교육성과 분석보고서 작성 건수",
    formula: "교육성과 분석보고서 작성 건수",
    dept: "혁신성과관리센터(IR)",
    actual: "4건",
    target: 4,
    unit: "건",
    linkedField: "education_outcome_report_count",
  },
  {
    id: "ltp-10",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "수업 질 관리 체계 강화",
    action: "CQI 환류 체계 운영",
    indicator: "수업개선 환류 사례 수",
    formula: "수업개선 환류 사례 수",
    dept: "교무처",
    actual: "12건",
    target: 10,
    unit: "건",
    linkedField: "teaching_improvement_feedback_count",
  },
  {
    id: "ltp-11",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "연계전공·융복합전공 개설 및 교과목 운영",
    action: "연계전공 교과목 개설 및 교과목 운영",
    indicator: "연계 교과목 신규 개발 건수",
    formula: "연계 교과목 신규 개발 건수",
    dept: "교무처",
    actual: "3건",
    target: 2,
    unit: "건",
  },
];

export const LTP_ROWS: LtpRow[] = LTP_ROWS_BASE.map((r) => ({
  ...r,
  years: ltpYearSeries(r.actual),
}));

// ---------------------------------------------------------------------------
// 4) 대학기관평가인증 — 교육혁신처 관련 발췌 (2023년~)
// ---------------------------------------------------------------------------
const EVALUATION_ROWS_BASE: Omit<EvaluationRow, "years">[] = [
  {
    id: "eval-01",
    area: "교육과정 운영 및 개선",
    item: "교육과정의 다양화·특성화",
    material: "에듀테크 활용 교과목 운영 현황",
    dept: "교육혁신처",
    relatedPerformance: "에듀테크 기반 수업 운영 교과목 수 18개",
    evidenceStatus: "제출완료",
    linkedField: "edutech_course_count",
  },
  {
    id: "eval-02",
    area: "교수학습 지원 체계",
    item: "학습관리시스템(LMS) 운영 실적",
    material: "LMS 활용 교과목 현황",
    dept: "교육혁신처",
    relatedPerformance: "LMS 활용 교과목 수 156개",
    evidenceStatus: "제출완료",
    linkedField: "lms_course_count",
  },
  {
    id: "eval-03",
    area: "교수학습 지원 체계",
    item: "교수법 다양화 및 학습자 중심 수업 운영",
    material: "혁신교수법 적용 교과목 목록 및 강의계획서",
    dept: "교육혁신처",
    relatedPerformance: "혁신교수법 적용 교과목 수 24개",
    evidenceStatus: "준비중",
    linkedField: "innovative_teaching_course_count",
  },
  {
    id: "eval-04",
    area: "교수학습 지원 체계",
    item: "교원 교수역량 개발 지원",
    material: "워크숍 운영계획 및 결과보고서",
    dept: "교수학습개발원",
    relatedPerformance: "교수법 워크숍 6건 · 참여 교원 86명",
    evidenceStatus: "제출완료",
    linkedField: "teaching_workshop_count",
  },
  {
    id: "eval-05",
    area: "학생역량 관리",
    item: "학생 핵심역량 진단·관리 체계",
    material: "역량진단 결과보고서",
    dept: "혁신성과관리센터(IR)",
    relatedPerformance: "학생역량 진단 참여 학생 수 246명",
    evidenceStatus: "준비중",
    linkedField: "student_competency_diagnosis_count",
  },
  {
    id: "eval-06",
    area: "학생역량 관리",
    item: "비교과 교육과정 운영 실적",
    material: "비교과 프로그램 참여자 명단",
    dept: "학생처",
    relatedPerformance: "비교과 프로그램 참여 학생 수 418명",
    evidenceStatus: "제출완료",
    linkedField: "extracurricular_program_participant_count",
  },
  {
    id: "eval-07",
    area: "교육성과 분석 및 환류",
    item: "강의평가 및 CQI 환류체계 운영",
    material: "CQI 보고서",
    dept: "교육혁신처",
    relatedPerformance: "CQI 보고서 제출 교과목 수 132개",
    evidenceStatus: "제출완료",
    linkedField: "cqi_report_count",
  },
  {
    id: "eval-08",
    area: "교육성과 분석 및 환류",
    item: "교육성과 분석체계 구축·운영",
    material: "교육성과 분석 보고서",
    dept: "혁신성과관리센터(IR)",
    relatedPerformance: "교육성과 분석보고서 작성 건수 4건",
    evidenceStatus: "미착수",
    linkedField: "education_outcome_report_count",
  },
  {
    id: "eval-09",
    area: "교육성과 분석 및 환류",
    item: "환류 결과의 활용 실적",
    material: "수업개선 사례집",
    dept: "교무처",
    relatedPerformance: "수업개선 환류 사례 수 12건",
    evidenceStatus: "준비중",
    linkedField: "teaching_improvement_feedback_count",
  },
  {
    id: "eval-10",
    area: "교육여건 및 재정",
    item: "교육시설 및 기자재 확보 실적",
    material: "실습·강의 기자재 현황",
    dept: "기획실",
    relatedPerformance: "-",
    evidenceStatus: "준비중",
  },
];

export const EVALUATION_ROWS: EvaluationRow[] = EVALUATION_ROWS_BASE.map((r) => ({
  ...r,
  years: evalYearSeries(r.relatedPerformance, r.evidenceStatus),
}));

// ---------------------------------------------------------------------------
// 5) 관리 자료 3종 요약
// ---------------------------------------------------------------------------
// 항상 "장기발전계획 → 대학기관평가인증 → 대학혁신지원사업" 순서로 노출
export const REPORT_SUMMARIES = [
  {
    key: "ltp",
    title: "장기발전계획",
    description: "장신비전 2030 4단계 · 2023~2026년 · 교육혁신처 실행과제 11개",
    href: "/long-term-plan",
    total: LTP_ROWS.length,
    linked: LTP_ROWS.filter((r) => r.linkedField).length,
    accent: "navy",
  },
  {
    key: "evaluation",
    title: "대학기관평가인증",
    description: "2023~2026년 · 4개 평가영역 10개 항목 · 증빙 준비 현황 포함",
    href: "/evaluation",
    total: EVALUATION_ROWS.length,
    linked: EVALUATION_ROWS.filter((r) => r.linkedField).length,
    accent: "maroon",
  },
  {
    key: "uisp",
    title: "대학혁신지원사업",
    description: `2025~2026년 · 자율성과지표 A~D ${UISP_INDICATORS.length}개 지표 (uisp.vercel.app 실데이터) · 교육혁신처 연계 ${UISP_INDICATORS.filter((r) => r.linkedField).length}개`,
    href: "/uisp",
    total: UISP_INDICATORS.length,
    linked: UISP_INDICATORS.filter((r) => r.linkedField).length,
    accent: "gold",
  },
] as const;

// ---------------------------------------------------------------------------
// 6) 문서형 보기 — HWP/Excel 문서를 웹으로 옮긴 형태 (2026년 최신 자료 기준)
//    항상 "장기발전계획 → 대학기관평가인증 → 대학혁신지원사업" 순서로 노출
// ---------------------------------------------------------------------------
export const DOCUMENTS: DocumentDef[] = [
  {
    key: "ltp",
    title: "장신비전 2030 4단계 장기발전계획 추진실적표",
    subtitle: "교육혁신처 (발췌) · 2026년 기준",
    owner: "교육혁신처",
    updatedAt: "2026-07-01",
    sections: [
      {
        title: "창의융합 미래선도형 교육과정 혁신",
        columns: [
          "추진과제",
          "실행과제",
          "성과지표",
          "지표산식",
          "담당부서",
          "목푯값",
          "실적",
          "달성률",
        ],
        rows: LTP_ROWS.map((r) => [
          r.task,
          r.action,
          r.indicator,
          r.formula,
          r.dept,
          `${r.target}${r.unit}`,
          r.actual,
          `${Math.round((r.years.find((y) => y.year === CURRENT_YEAR)!.actualValue / r.target) * 100)}%`,
        ]),
        linkedFieldColumnIndex: 2,
        linkedRows: LTP_ROWS.map((r) => Boolean(r.linkedField)),
      },
    ],
  },
  {
    key: "evaluation",
    title: "대학기관평가인증 자체진단 보고서",
    subtitle: "교육과정·교수학습·학생역량·성과환류 영역 (발췌) · 2026년 기준",
    owner: "혁신성과관리센터(IR)",
    updatedAt: "2026-06-28",
    sections: [
      {
        title: "평가영역별 요구자료 및 증빙 현황",
        columns: ["평가영역", "평가항목", "요구자료", "담당부서", "관련 실적", "증빙상태"],
        rows: EVALUATION_ROWS.map((r) => [
          r.area,
          r.item,
          r.material,
          r.dept,
          r.relatedPerformance,
          r.evidenceStatus,
        ]),
        linkedFieldColumnIndex: 1,
        linkedRows: EVALUATION_ROWS.map((r) => Boolean(r.linkedField)),
      },
    ],
  },
  {
    key: "uisp",
    title: "2026년 대학혁신지원사업 자율성과지표 실적표",
    subtitle: "uisp.vercel.app · 지표 상세 (발췌) · 대학(학부) 몫만 반영",
    owner: "교육혁신처",
    updatedAt: "2026-07-03",
    sections: [
      {
        title: "A. 학사 유연화 지수",
        columns: ["코드", "지표명", "담당부서", "기준값", "목푯값", "실적값", "달성도"],
        rows: UISP_INDICATORS.filter((r) => r.area === "A").map((r) => [
          r.code,
          r.indicator,
          r.dept,
          `${r.baseline}${r.unit}`,
          `${r.target}${r.unit}`,
          `${r.actual}${r.unit}`,
          `${attainmentPct(r.actual, r.target)}%`,
        ]),
        linkedFieldColumnIndex: 1,
        linkedRows: UISP_INDICATORS.filter((r) => r.area === "A").map((r) => Boolean(r.linkedField)),
      },
      {
        title: "B. 학생성장 지원 지수",
        columns: ["코드", "지표명", "담당부서", "기준값", "목푯값", "실적값", "달성도"],
        rows: UISP_INDICATORS.filter((r) => r.area === "B").map((r) => [
          r.code,
          r.indicator,
          r.dept,
          `${r.baseline}${r.unit}`,
          `${r.target}${r.unit}`,
          `${r.actual}${r.unit}`,
          `${attainmentPct(r.actual, r.target)}%`,
        ]),
        linkedFieldColumnIndex: 1,
        linkedRows: UISP_INDICATORS.filter((r) => r.area === "B").map((r) => Boolean(r.linkedField)),
      },
      {
        title: "C. PUTS형 교육혁신 지수",
        columns: ["코드", "지표명", "담당부서", "기준값", "목푯값", "실적값", "달성도"],
        rows: UISP_INDICATORS.filter((r) => r.area === "C").map((r) => [
          r.code,
          r.indicator,
          r.dept,
          `${r.baseline}${r.unit}`,
          `${r.target}${r.unit}`,
          `${r.actual}${r.unit}`,
          `${attainmentPct(r.actual, r.target)}%`,
        ]),
        linkedFieldColumnIndex: 1,
        linkedRows: UISP_INDICATORS.filter((r) => r.area === "C").map((r) => Boolean(r.linkedField)),
      },
      {
        title: "D. 교육환경 고도화 지수",
        columns: ["코드", "지표명", "담당부서", "기준값", "목푯값", "실적값", "달성도"],
        rows: UISP_INDICATORS.filter((r) => r.area === "D").map((r) => [
          r.code,
          r.indicator,
          r.dept,
          `${r.baseline}${r.unit}`,
          `${r.target}${r.unit}`,
          `${r.actual}${r.unit}`,
          `${attainmentPct(r.actual, r.target)}%`,
        ]),
        linkedFieldColumnIndex: 1,
        linkedRows: UISP_INDICATORS.filter((r) => r.area === "D").map((r) => Boolean(r.linkedField)),
      },
    ],
  },
];
