import type {
  CommonIndicator,
  UispIndicatorRow,
  LtpRow,
  EvaluationRow,
  DocumentDef,
} from "./types";

export const CURRENT_PERIOD = "2026학년도 1학기";

// ---------------------------------------------------------------------------
// 1) 교육혁신처 기준 공통 실적 데이터 10종
//    -> 대학혁신지원사업 / 장기발전계획 / 대학평가 3개 장표와의 연계 매핑
// ---------------------------------------------------------------------------
export const COMMON_INDICATORS: CommonIndicator[] = [
  {
    field: "edutech_course_count",
    sourceLabel: "에듀테크 기반 수업 운영 교과목 수",
    value: 18,
    unit: "개",
    dept: "교육혁신처",
    period: CURRENT_PERIOD,
    group: "에듀테크·혁신교수법",
    uisp: {
      area: "C",
      code: "C111",
      indicator: "에듀테크 활용 교과 운영 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "교육혁신 체계 고도화",
      action: "에듀테크 기반 수업환경 조성",
      indicator: "에듀테크 활용 교과목 운영 수",
    },
    evaluation: {
      area: "교육과정 운영 및 개선",
      item: "교육과정의 다양화·특성화",
      material: "에듀테크 활용 교과목 운영 현황",
    },
  },
  {
    field: "innovative_teaching_course_count",
    sourceLabel: "혁신교수법 적용 교과목 수",
    value: 24,
    unit: "개",
    dept: "교육혁신처",
    period: CURRENT_PERIOD,
    group: "에듀테크·혁신교수법",
    uisp: {
      area: "C",
      code: "C112",
      indicator: "혁신교수법 적용 교과 운영 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "미래형 교수학습 지원 강화",
      action: "혁신교수법(PBL·플립러닝 등) 확산",
      indicator: "혁신교수법 적용 교과목 수",
    },
    evaluation: {
      area: "교수학습 지원 체계",
      item: "교수법 다양화 및 학습자 중심 수업 운영",
      material: "혁신교수법 적용 교과목 목록 및 강의계획서",
    },
  },
  {
    field: "teaching_workshop_count",
    sourceLabel: "교수법 워크숍 운영 건수",
    value: 6,
    unit: "건",
    dept: "교수학습개발원",
    period: CURRENT_PERIOD,
    group: "교수역량 워크숍",
    uisp: {
      area: "C",
      code: "C131",
      indicator: "교수역량 강화 프로그램(기존) 운영 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "미래형 교수학습 지원 강화",
      action: "교원 교수역량 강화 워크숍 운영",
      indicator: "교수법 워크숍 운영 건수",
    },
    evaluation: {
      area: "교수학습 지원 체계",
      item: "교원 교수역량 개발 지원",
      material: "워크숍 운영계획 및 결과보고서",
    },
  },
  {
    field: "teaching_workshop_participant_count",
    sourceLabel: "교수법 워크숍 참여 교원 수",
    value: 86,
    unit: "명",
    dept: "교수학습개발원",
    period: CURRENT_PERIOD,
    group: "교수역량 워크숍",
    uisp: {
      area: "C",
      code: "C232",
      indicator: "강화 프로그램 참여 교원 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "미래형 교수학습 지원 강화",
      action: "교원 교수역량 강화 워크숍 운영",
      indicator: "워크숍 참여 교원 수",
    },
    evaluation: {
      area: "교수학습 지원 체계",
      item: "교원 교수역량 개발 지원",
      material: "워크숍 참여자 명단",
    },
  },
  {
    field: "cqi_report_count",
    sourceLabel: "CQI 보고서 제출 교과목 수",
    value: 132,
    unit: "개",
    dept: "교육혁신처",
    period: CURRENT_PERIOD,
    group: "성과분석·환류",
    uisp: {
      area: "C",
      code: "C121",
      indicator: "CQI 입력 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "수업 질 관리 체계 강화",
      action: "CQI 환류 체계 운영",
      indicator: "교과목 CQI 참여율",
    },
    evaluation: {
      area: "교육성과 분석 및 환류",
      item: "강의평가 및 CQI 환류체계 운영",
      material: "CQI 보고서",
    },
  },
  {
    field: "student_competency_diagnosis_count",
    sourceLabel: "학생역량 진단 참여 학생 수",
    value: 246,
    unit: "명",
    dept: "혁신성과관리센터(IR)",
    period: CURRENT_PERIOD,
    group: "학생역량·비교과",
    uisp: {
      area: "C",
      code: "C221",
      indicator: "역량진단・강화 프로그램(기존) 참여 학생 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "학생역량 기반 교육성과 관리",
      action: "핵심역량 진단검사 실시",
      indicator: "역량진단 참여 학생 수",
    },
    evaluation: {
      area: "학생역량 관리",
      item: "학생 핵심역량 진단·관리 체계",
      material: "역량진단 결과보고서",
    },
  },
  {
    field: "extracurricular_program_participant_count",
    sourceLabel: "비교과 프로그램 참여 학생 수",
    value: 418,
    unit: "명",
    dept: "학생처",
    period: CURRENT_PERIOD,
    group: "학생역량·비교과",
    uisp: {
      area: "B",
      code: "B2",
      indicator: "학생성장 프로그램 참여 학생 수",
    },
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "학생역량 기반 교육성과 관리",
      action: "비교과 프로그램 운영 및 참여 확대",
      indicator: "비교과 프로그램 참여 학생 수",
    },
    evaluation: {
      area: "학생역량 관리",
      item: "비교과 교육과정 운영 실적",
      material: "비교과 프로그램 참여자 명단",
    },
  },
  {
    field: "lms_course_count",
    sourceLabel: "LMS 활용 교과목 수",
    value: 156,
    unit: "개",
    dept: "교육혁신처",
    period: CURRENT_PERIOD,
    group: "에듀테크·혁신교수법",
    // uisp.vercel.app 자율성과지표에는 "LMS 이용자 수(D21)"만 있고 "교과목 수" 단위의
    // 동일 지표가 없어 UISP 연계는 아직 없음 (장기발전계획·대학평가에서만 활용)
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "교육혁신 체계 고도화",
      action: "LMS 기반 학습관리 확대",
      indicator: "LMS 활용 교과목 수",
    },
    evaluation: {
      area: "교수학습 지원 체계",
      item: "학습관리시스템(LMS) 운영 실적",
      material: "LMS 활용 교과목 현황",
    },
  },
  {
    field: "education_outcome_report_count",
    sourceLabel: "교육성과 분석 보고서 작성 건수",
    value: 4,
    unit: "건",
    dept: "혁신성과관리센터(IR)",
    period: CURRENT_PERIOD,
    group: "성과분석·환류",
    // uisp.vercel.app에는 보고서 "작성 건수"를 세는 지표가 없어 UISP 연계는 아직 없음
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "수업 질 관리 체계 강화",
      action: "교육성과 분석 및 확산",
      indicator: "교육성과 분석보고서 작성 건수",
    },
    evaluation: {
      area: "교육성과 분석 및 환류",
      item: "교육성과 분석체계 구축·운영",
      material: "교육성과 분석 보고서",
    },
  },
  {
    field: "teaching_improvement_feedback_count",
    sourceLabel: "수업 개선 환류 사례 수",
    value: 12,
    unit: "건",
    dept: "교무처",
    period: CURRENT_PERIOD,
    group: "성과분석·환류",
    // uisp.vercel.app에는 "환류 사례 수"에 대응하는 지표가 없어 UISP 연계는 아직 없음
    ltp: {
      strategy: "창의융합 미래선도형 교육과정 혁신",
      task: "수업 질 관리 체계 강화",
      action: "CQI 환류 체계 운영",
      indicator: "수업개선 환류 사례 수",
    },
    evaluation: {
      area: "교육성과 분석 및 환류",
      item: "환류 결과의 활용 실적",
      material: "수업개선 사례집",
    },
  },
];

// ---------------------------------------------------------------------------
// 2) 대학혁신지원사업 (UISP) — uisp.vercel.app 실제 자율성과지표 A~D 체계 그대로 사용
//    (지표 코드·지표명·담당부서는 yenna-ai/uisp 저장소의 Indicators.csv / Users.csv 기준)
//    linkedField 가 있는 행은 교육혁신처 공통 데이터와 연결된 지표
// ---------------------------------------------------------------------------
export const UISP_AREAS = [
  { code: "A", name: "학사 유연화 지수", short: "학사 유연화" },
  { code: "B", name: "학생성장 지원 지수", short: "학생성장 지원" },
  { code: "C", name: "PUTS형 교육혁신 지수", short: "PUTS형 교육혁신" },
  { code: "D", name: "교육환경 고도화 지수", short: "교육환경 고도화" },
] as const;

export const UISP_INDICATORS: UispIndicatorRow[] = [
  {
    id: "A11",
    area: "A",
    code: "A11",
    indicator: "자유전공 전공탐색 교과 개발 수",
    dept: "교육혁신처",
    baseline: 1,
    target: 2,
    actual: 2,
    unit: "개",
  },
  {
    id: "A121",
    area: "A",
    code: "A121",
    indicator: "교양기초교육 신규교과 개발 수",
    dept: "교육혁신처",
    baseline: 2,
    target: 3,
    actual: 3,
    unit: "개",
  },
  {
    id: "A13",
    area: "A",
    code: "A13",
    indicator: "연계・융합전공 교과 개발 수",
    dept: "교육혁신처",
    baseline: 1,
    target: 2,
    actual: 3,
    unit: "개",
  },
  {
    id: "B1",
    area: "B",
    code: "B1",
    indicator: "학생성장 프로그램 운영 수",
    dept: "학생생활상담소",
    baseline: 5,
    target: 6,
    actual: 7,
    unit: "개",
  },
  {
    id: "B2",
    area: "B",
    code: "B2",
    indicator: "학생성장 프로그램 참여 학생 수",
    dept: "학생생활상담소",
    baseline: 300,
    target: 350,
    actual: 418,
    unit: "명",
    linkedField: "extracurricular_program_participant_count",
  },
  {
    id: "B24",
    area: "B",
    code: "B24",
    indicator: "PUTS+마일리지・인증제 참여 학생 수",
    dept: "교육혁신처",
    baseline: 120,
    target: 150,
    actual: 168,
    unit: "명",
  },
  {
    id: "B3",
    area: "B",
    code: "B3",
    indicator: "학생성장 프로그램 만족도 평균",
    dept: "학생생활상담소",
    baseline: 4.0,
    target: 4.2,
    actual: 4.3,
    unit: "점",
  },
  {
    id: "C111",
    area: "C",
    code: "C111",
    indicator: "에듀테크 활용 교과 운영 수",
    dept: "교육혁신처(CTL)",
    baseline: 10,
    target: 15,
    actual: 18,
    unit: "개",
    linkedField: "edutech_course_count",
  },
  {
    id: "C112",
    area: "C",
    code: "C112",
    indicator: "혁신교수법 적용 교과 운영 수",
    dept: "교육혁신처(CTL)",
    baseline: 15,
    target: 20,
    actual: 24,
    unit: "개",
    linkedField: "innovative_teaching_course_count",
  },
  {
    id: "C121",
    area: "C",
    code: "C121",
    indicator: "CQI 입력 수",
    dept: "교육혁신처(IR)",
    baseline: 100,
    target: 120,
    actual: 132,
    unit: "개",
    linkedField: "cqi_report_count",
  },
  {
    id: "C122",
    area: "C",
    code: "C122",
    indicator: "우수 교과 확산 수",
    dept: "교육혁신처(IR)",
    baseline: 5,
    target: 8,
    actual: 9,
    unit: "개",
  },
  {
    id: "C131",
    area: "C",
    code: "C131",
    indicator: "교수역량 강화 프로그램(기존) 운영 수",
    dept: "교육혁신처(CTL)",
    baseline: 3,
    target: 4,
    actual: 6,
    unit: "건",
    linkedField: "teaching_workshop_count",
  },
  {
    id: "C221",
    area: "C",
    code: "C221",
    indicator: "역량진단・강화 프로그램(기존) 참여 학생 수",
    dept: "교육혁신처(IR)",
    baseline: 180,
    target: 200,
    actual: 246,
    unit: "명",
    linkedField: "student_competency_diagnosis_count",
  },
  {
    id: "C232",
    area: "C",
    code: "C232",
    indicator: "강화 프로그램 참여 교원 수",
    dept: "교육혁신처(CTL)",
    baseline: 50,
    target: 70,
    actual: 86,
    unit: "명",
    linkedField: "teaching_workshop_participant_count",
  },
  {
    id: "C41",
    area: "C",
    code: "C41",
    indicator: "학생 핵심역량 진단 점수",
    dept: "교육혁신처(IR)",
    baseline: 3.6,
    target: 3.8,
    actual: 3.9,
    unit: "점",
  },
  {
    id: "D111",
    area: "D",
    code: "D111",
    indicator: "LMS 개발・운영 수",
    dept: "교육혁신처(CTL)",
    baseline: 1,
    target: 2,
    actual: 2,
    unit: "개",
  },
  {
    id: "D12",
    area: "D",
    code: "D12",
    indicator: "에듀테크 라이선스 확보・지원 수",
    dept: "교육혁신처(CTL)",
    baseline: 2,
    target: 3,
    actual: 3,
    unit: "건",
  },
  {
    id: "D21",
    area: "D",
    code: "D21",
    indicator: "LMS 이용자 수",
    dept: "교육혁신처(CTL)",
    baseline: 2000,
    target: 2200,
    actual: 2350,
    unit: "명",
  },
];

// ---------------------------------------------------------------------------
// 3) 장기발전계획(장신비전 2030 4단계) — 교육혁신처 관련 발췌
// ---------------------------------------------------------------------------
export const LTP_ROWS: LtpRow[] = [
  {
    id: "ltp-01",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "교육혁신 체계 고도화",
    action: "에듀테크 기반 수업환경 조성",
    indicator: "에듀테크 활용 교과목 운영 수",
    formula: "에듀테크 활용 교과목 수",
    dept: "교육혁신처",
    actual: "18개",
    linkedField: "edutech_course_count",
  },
  {
    id: "ltp-02",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "교육혁신 체계 고도화",
    action: "LMS 기반 학습관리 확대",
    indicator: "LMS 활용 교과목 수",
    formula: "LMS 활용 교과목 수",
    dept: "교육혁신처",
    actual: "156개",
    linkedField: "lms_course_count",
  },
  {
    id: "ltp-03",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "미래형 교수학습 지원 강화",
    action: "혁신교수법(PBL·플립러닝 등) 확산",
    indicator: "혁신교수법 적용 교과목 수",
    formula: "혁신교수법 적용 교과목 수",
    dept: "교육혁신처",
    actual: "24개",
    linkedField: "innovative_teaching_course_count",
  },
  {
    id: "ltp-04",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "미래형 교수학습 지원 강화",
    action: "교원 교수역량 강화 워크숍 운영",
    indicator: "교수법 워크숍 운영 건수",
    formula: "워크숍 운영 건수",
    dept: "교수학습개발원",
    actual: "6건",
    linkedField: "teaching_workshop_count",
  },
  {
    id: "ltp-05",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "미래형 교수학습 지원 강화",
    action: "교원 교수역량 강화 워크숍 운영",
    indicator: "워크숍 참여 교원 수",
    formula: "워크숍 참여 교원 수",
    dept: "교수학습개발원",
    actual: "86명",
    linkedField: "teaching_workshop_participant_count",
  },
  {
    id: "ltp-06",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "학생역량 기반 교육성과 관리",
    action: "핵심역량 진단검사 실시",
    indicator: "역량진단 참여 학생 수",
    formula: "역량진단 참여 학생 수",
    dept: "혁신성과관리센터(IR)",
    actual: "246명",
    linkedField: "student_competency_diagnosis_count",
  },
  {
    id: "ltp-07",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "학생역량 기반 교육성과 관리",
    action: "비교과 프로그램 운영 및 참여 확대",
    indicator: "비교과 프로그램 참여 학생 수",
    formula: "비교과 프로그램 참여 학생 수(연인원)",
    dept: "학생처",
    actual: "418명",
    linkedField: "extracurricular_program_participant_count",
  },
  {
    id: "ltp-08",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "수업 질 관리 체계 강화",
    action: "CQI 환류 체계 운영",
    indicator: "교과목 CQI 참여율",
    formula: "CQI 제출 교과목 수 / 매 학기 전체 교과목 수 X 100",
    dept: "교육혁신처",
    actual: "132개 제출",
    linkedField: "cqi_report_count",
  },
  {
    id: "ltp-09",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "수업 질 관리 체계 강화",
    action: "교육성과 분석 및 확산",
    indicator: "교육성과 분석보고서 작성 건수",
    formula: "교육성과 분석보고서 작성 건수",
    dept: "혁신성과관리센터(IR)",
    actual: "4건",
    linkedField: "education_outcome_report_count",
  },
  {
    id: "ltp-10",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "수업 질 관리 체계 강화",
    action: "CQI 환류 체계 운영",
    indicator: "수업개선 환류 사례 수",
    formula: "수업개선 환류 사례 수",
    dept: "교무처",
    actual: "12건",
    linkedField: "teaching_improvement_feedback_count",
  },
  {
    id: "ltp-11",
    strategy: "창의융합 미래선도형 교육과정 혁신",
    task: "연계전공·융복합전공 개설 및 교과목 운영",
    action: "연계전공 교과목 개설 및 교과목 운영",
    indicator: "연계 교과목 신규 개발 건수",
    formula: "연계 교과목 신규 개발 건수",
    dept: "교무처",
    actual: "3건",
  },
];

// ---------------------------------------------------------------------------
// 4) 대학평가 — 교육혁신처 관련 발췌
// ---------------------------------------------------------------------------
export const EVALUATION_ROWS: EvaluationRow[] = [
  {
    id: "eval-01",
    area: "교육과정 운영 및 개선",
    item: "교육과정의 다양화·특성화",
    material: "에듀테크 활용 교과목 운영 현황",
    dept: "교육혁신처",
    relatedPerformance: "에듀테크 기반 수업 운영 교과목 수 18개",
    evidenceStatus: "제출완료",
    linkedField: "edutech_course_count",
  },
  {
    id: "eval-02",
    area: "교수학습 지원 체계",
    item: "학습관리시스템(LMS) 운영 실적",
    material: "LMS 활용 교과목 현황",
    dept: "교육혁신처",
    relatedPerformance: "LMS 활용 교과목 수 156개",
    evidenceStatus: "제출완료",
    linkedField: "lms_course_count",
  },
  {
    id: "eval-03",
    area: "교수학습 지원 체계",
    item: "교수법 다양화 및 학습자 중심 수업 운영",
    material: "혁신교수법 적용 교과목 목록 및 강의계획서",
    dept: "교육혁신처",
    relatedPerformance: "혁신교수법 적용 교과목 수 24개",
    evidenceStatus: "준비중",
    linkedField: "innovative_teaching_course_count",
  },
  {
    id: "eval-04",
    area: "교수학습 지원 체계",
    item: "교원 교수역량 개발 지원",
    material: "워크숍 운영계획 및 결과보고서",
    dept: "교수학습개발원",
    relatedPerformance: "교수법 워크숍 6건 · 참여 교원 86명",
    evidenceStatus: "제출완료",
    linkedField: "teaching_workshop_count",
  },
  {
    id: "eval-05",
    area: "학생역량 관리",
    item: "학생 핵심역량 진단·관리 체계",
    material: "역량진단 결과보고서",
    dept: "혁신성과관리센터(IR)",
    relatedPerformance: "학생역량 진단 참여 학생 수 246명",
    evidenceStatus: "준비중",
    linkedField: "student_competency_diagnosis_count",
  },
  {
    id: "eval-06",
    area: "학생역량 관리",
    item: "비교과 교육과정 운영 실적",
    material: "비교과 프로그램 참여자 명단",
    dept: "학생처",
    relatedPerformance: "비교과 프로그램 참여 학생 수 418명",
    evidenceStatus: "제출완료",
    linkedField: "extracurricular_program_participant_count",
  },
  {
    id: "eval-07",
    area: "교육성과 분석 및 환류",
    item: "강의평가 및 CQI 환류체계 운영",
    material: "CQI 보고서",
    dept: "교육혁신처",
    relatedPerformance: "CQI 보고서 제출 교과목 수 132개",
    evidenceStatus: "제출완료",
    linkedField: "cqi_report_count",
  },
  {
    id: "eval-08",
    area: "교육성과 분석 및 환류",
    item: "교육성과 분석체계 구축·운영",
    material: "교육성과 분석 보고서",
    dept: "혁신성과관리센터(IR)",
    relatedPerformance: "교육성과 분석보고서 작성 건수 4건",
    evidenceStatus: "미착수",
    linkedField: "education_outcome_report_count",
  },
  {
    id: "eval-09",
    area: "교육성과 분석 및 환류",
    item: "환류 결과의 활용 실적",
    material: "수업개선 사례집",
    dept: "교무처",
    relatedPerformance: "수업개선 환류 사례 수 12건",
    evidenceStatus: "준비중",
    linkedField: "teaching_improvement_feedback_count",
  },
  {
    id: "eval-10",
    area: "교육여건 및 재정",
    item: "교육시설 및 기자재 확보 실적",
    material: "실습·강의 기자재 현황",
    dept: "기획실",
    relatedPerformance: "-",
    evidenceStatus: "준비중",
  },
];

// ---------------------------------------------------------------------------
// 5) 통합 현황 요약
// ---------------------------------------------------------------------------
export const OVERVIEW_SUMMARY = {
  managedDocuments: 3,
  commonIndicatorCount: COMMON_INDICATORS.length,
  linkedReportItemCount:
    UISP_INDICATORS.filter((r) => r.linkedField).length +
    LTP_ROWS.filter((r) => r.linkedField).length +
    EVALUATION_ROWS.filter((r) => r.linkedField).length,
  duplicateSubmissionReduction: 60,
};

export const REPORT_SUMMARIES = [
  {
    key: "uisp",
    title: "대학혁신지원사업",
    description: "자율성과지표 A~D 18개 지표 · 교육혁신처 연계 7개 (uisp.vercel.app 용어 기준)",
    href: "/uisp",
    total: UISP_INDICATORS.length,
    linked: UISP_INDICATORS.filter((r) => r.linkedField).length,
    accent: "blue",
  },
  {
    key: "ltp",
    title: "장기발전계획",
    description: "장신비전 2030 4단계 · 교육혁신처 실행과제 11개",
    href: "/long-term-plan",
    total: LTP_ROWS.length,
    linked: LTP_ROWS.filter((r) => r.linkedField).length,
    accent: "indigo",
  },
  {
    key: "evaluation",
    title: "대학평가",
    description: "4개 평가영역 10개 항목 · 증빙 준비 현황 포함",
    href: "/evaluation",
    total: EVALUATION_ROWS.length,
    linked: EVALUATION_ROWS.filter((r) => r.linkedField).length,
    accent: "teal",
  },
] as const;

// ---------------------------------------------------------------------------
// 6) 문서형 보기 — HWP/Excel 문서를 웹으로 옮긴 형태
// ---------------------------------------------------------------------------
export const DOCUMENTS: DocumentDef[] = [
  {
    key: "uisp",
    title: "2026년 대학혁신지원사업 자율성과지표 실적표",
    subtitle: "uisp.vercel.app · 지표 상세 (발췌)",
    owner: "교육혁신처",
    updatedAt: "2026-07-03",
    sections: [
      {
        title: "C. PUTS형 교육혁신 지수",
        columns: ["코드", "지표명", "담당부서", "기준값", "목푯값", "실적값", "달성도"],
        rows: UISP_INDICATORS.filter((r) => r.area === "C").map((r) => [
          r.code,
          r.indicator,
          r.dept,
          `${r.baseline}${r.unit}`,
          `${r.target}${r.unit}`,
          `${r.actual}${r.unit}`,
          `${Math.round((r.actual / r.target) * 100)}%`,
        ]),
        linkedFieldColumnIndex: 1,
        linkedRows: UISP_INDICATORS.filter((r) => r.area === "C").map((r) => Boolean(r.linkedField)),
      },
      {
        title: "D. 교육환경 고도화 지수",
        columns: ["코드", "지표명", "담당부서", "기준값", "목푯값", "실적값", "달성도"],
        rows: UISP_INDICATORS.filter((r) => r.area === "D").map((r) => [
          r.code,
          r.indicator,
          r.dept,
          `${r.baseline}${r.unit}`,
          `${r.target}${r.unit}`,
          `${r.actual}${r.unit}`,
          `${Math.round((r.actual / r.target) * 100)}%`,
        ]),
        linkedFieldColumnIndex: 1,
        linkedRows: UISP_INDICATORS.filter((r) => r.area === "D").map((r) => Boolean(r.linkedField)),
      },
    ],
  },
  {
    key: "ltp",
    title: "장신비전 2030 4단계 장기발전계획 추진실적표",
    subtitle: "교육혁신처 (발췌)",
    owner: "교육혁신처",
    updatedAt: "2026-07-01",
    sections: [
      {
        title: "창의융합 미래선도형 교육과정 혁신",
        columns: ["추진과제", "실행과제", "성과지표", "지표산식", "담당부서", "실적"],
        rows: LTP_ROWS.map((r) => [
          r.task,
          r.action,
          r.indicator,
          r.formula,
          r.dept,
          r.actual,
        ]),
        linkedFieldColumnIndex: 2,
        linkedRows: LTP_ROWS.map((r) => Boolean(r.linkedField)),
      },
    ],
  },
  {
    key: "evaluation",
    title: "대학평가 자체진단 보고서",
    subtitle: "교육과정·교수학습·학생역량·성과환류 영역 (발췌)",
    owner: "혁신성과관리센터(IR)",
    updatedAt: "2026-06-28",
    sections: [
      {
        title: "평가영역별 요구자료 및 증빙 현황",
        columns: ["평가영역", "평가항목", "요구자료", "담당부서", "관련 실적", "증빙상태"],
        rows: EVALUATION_ROWS.map((r) => [
          r.area,
          r.item,
          r.material,
          r.dept,
          r.relatedPerformance,
          r.evidenceStatus,
        ]),
        linkedFieldColumnIndex: 1,
        linkedRows: EVALUATION_ROWS.map((r) => Boolean(r.linkedField)),
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// 7) 최근 연결 예시 (통합 현황 하단 표)
// ---------------------------------------------------------------------------
export const RECENT_LINKS = COMMON_INDICATORS.slice(0, 5).map((c) => ({
  sourceLabel: c.sourceLabel,
  value: `${c.value}${c.unit}`,
  dept: c.dept,
  uisp: c.uisp?.indicator ?? "미연계",
  ltp: c.ltp.indicator,
  evaluation: c.evaluation.item,
}));
